### ISSUE TITLE
Is it necessary to pin anndata? 

### ISSUE THREAD

**Issue by grst** [MICS-Lab/scyan#30]
Hi @quentinblampey, 

I was wondering if there's a good reason to pin anndata to 0.8? A lot of new features and bugfixes have been added since then and I can't read `zarr` files that were generated by newer versions of AnnData. 

I understand that poetry advocates for these restrictive dependencies, but from scverse perspective, there shouldn't be any reason to pin old versions of anndata. Instead, we recommend setting up the CI to test against release candidates and report back if something breaks. 

Cheers, 
Gregor

**Comment by quentinblampey** [comment]
Hello @grst,

There is no reason for this, you're right, probably a mistake.

I'll update the dependencies versions in a future release, I'll let you know!

**Comment by quentinblampey** [comment]
The dependencies are updated in `scyan==1.6.0`!
