### ISSUE TITLE
Matplotlib Version got bumped up to 3.9.0 -> change in location of get_cmap function

### ISSUE THREAD

**Issue by dansteiert** [MICS-Lab/scyan#35]
## Description
cannot import name 'get_cmap' from 'matplotlib.cm' -> this got moved to matplotlib.pyplot.getcmap (https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.get_cmap.html )

## Reproducing the issue
pip install scyan
import scyan

## Expected behavior
No error

## System
 - OS: Linux
 - Python version 3.9.19
 - matplotlib=3.9.0 
<details>
<summary>Dependencies versions</summary>
<br>
Paste here what 'pip list' gives you.
</details>

**Comment by dansteiert** [comment]
downgrading matplotlib worked.
alternatively, the new version moved the get_cmap function to matplotlib.pyplot.get_cmap

**Comment by quentinblampey** [comment]
Thanks @dansteiert for reporting this! Since it's an major issue, I'll do a hotfix-release in the next few hours

**Comment by quentinblampey** [comment]
This is now fixed in `scyan==1.6.2`!
