### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Maelle83** [MICS-Lab/scyan#38]

**Comment by quentinblampey** [comment]
Hello @Maelle83,

Sorry I'm not really familiar with reticulate. I have a few questions though:
- is there a reason why you cloned the scyan repository? You can install it via `pip install scyan`
- do you have the same issue when using scyan with Python?
- you used the command `scyan$model`, but in python we do `scyan.Scyan` to initialize the model. So shouldn't your command be something like `scyan$Scyan`?
